### ISSUE TITLE
IPIP and VXLAN not support IPv6 addresses

### ISSUE THREAD

**Issue by lyyao09** [projectcalico/node#493] opened 2020-05-11 08:01 UTC
Our project needs to be deployed in across networks scenarios, so we are going to use calico's ipip mode. But from the official website, we see  ipip mode does not support ipv6. The relevant code also seems to limit ipip to only support ipv4 as follows:

https://github.com/projectcalico/node/blob/fc5311f58fe479eabe55101e91fc3a3ff45b39b1/pkg/allocateip/allocateip.go#L425-L428

So, what‘s the reason of not supporting this feature and whether it can provide support?

## Expected Behavior

IP in IP and VXLAN support IPv6 addresses.
## Current Behavior

IP in IP and VXLAN support only IPv4 addresses.
reference: https://docs.projectcalico.org/networking/vxlan-ipip
## Your Environment

* calico/node version: v3.7.4
* Operating System and version: CentOS 7.5

**Comment by lyyao09** [comment] 2020-05-12 01:46
From ipip [rfc2003](https://tools.ietf.org/html/rfc2003), I found that ipip mode only supports ipv4. I guess that's why ipip mode does not support ipv6.

Is vlxan a similar reason?

**Comment by caseydavenport** [comment] 2020-05-13 19:32
Closing as a duplicate of https://github.com/projectcalico/libcalico-go/issues/996

VXLAN should be possible, but we haven't implemented it. We expect that in most IPv6 scenarios, encap is not desired, since the primary reason for using IPv6 is extended address range support. 

Happy to discuss use-cases for this on the other issue.

**Closed by caseydavenport** 2020-05-13 19:32 UTC

**Comment by svallala** [comment] 2021-01-08 20:39
@caseydavenport we have a similar requirement where the operator is fully ipv6. There is a need to deploy K8s cluster across multiple DCs, which are in different v6 subnets. Without support for some kind of encapsulation, the only way to support a stretched cluster, in this case, would be to do BGP peering across all the routers in the path between the two DCs. Can you please suggest if there is any other way?

**Comment by svallala** [comment] 2021-05-11 00:52
@caseydavenport any comments regarding this requirement. Is there any way we can achieve this today for v6 clusters?
